westerndigitalcorporation/zonedstorage.io

- docs/getting-started/nullblk.md
s/method for creating/way to create/
Every time I re-read this material, I have a
better idea of what it means to communicate,
and every time I re-read this material I am
able to revise the English so that it sounds
more natural.
> doc: nullblk.md - improve wording

- docs/getting-started/smr-disk.md
This PR rewrites the overview text at the
top of the "Getting Started with SMR Disks"
chapter of the Getting Started Guide.
There are some phrases in this document that cry out
to me for revision ("LBA space zoning information"),
but experience has taught me to await further experience
before I begin revising this.
When I have finished revising this guide, I will no doubt
return to this text in order to revise it yet again.
All writing is rewriting. Einmal ist keinmal.
> doc: rewrite smr-disk.md top matter

- docs/getting-started/smr-emulation.md
There were a couple of minor article-related
typos in a sentence, and they bugged me enough
to drive me to make this PR.
This PR is minor, but the sentences that it
touches are now smoother.
> doc: smr-emulation.md typo correction

- Makefile
Signed-off-by: Matias Bjørling <matias.bjorling@wdc.com>
> Fix yui-compressor to apply only in the case that yui-compressor is available.

- cinder/base.html
Signed-off-by: Matias Bjørling <matias.bjorling@wdc.com>
> Update copyright year to 2021

- .github/workflows/main.yml
- requirements.txt
Add github action to verify that the
documentation can be built.
The action will be run on each pull request.
Signed-off-by: Matias Bjørling <matias.bjorling@wdc.com>
> workflow: verify mkdocs build

- docusaurus.config.js
Fix the link URL.
Signed-off-by: Naohiro Aota <naohiro.aota@wdc.com>
> fix dead link of "Getting Started with Zoned Storage"

- docs/linux/fs.md
Improve the documentation and examples for btrfs.
Signed-off-by: Johannes Thumshirn <johannes.thumshirn@wdc.com>
> docs: linux: improve btrfs section

- docs/linux/dm.md
This updates the second half of the "Device Mapper page.
Most of the updates in this file are typical
present-participle-to-relative-clause changes, but there
are a couple of sentences in this half that require significant
rewriting. I plan to use this PR to have a discussion that will
result in that rewriting.
> doc: update second half of dm.md

- docs/linux/fs.md
This is a grammar-and-elegance edit of the first
forty percent of fs.md.
I have marked a few difficult passages with TODO.
These still have to be rewritten. I request Damien's
clarifications on them.
> fs.md - first 40 percent

- docs/linux/fs.md
This PR rewrites the fs.md file up to (but
excluding) the "I/O Management" section.
I have chosed to break off here, because there
are two sentences in this section that require
elucidation and the I/O Management section will
require significant clarification. So I thought
that we would take care of this before continuing.
> doc: rewrite fs.md up to i/o management

- docs/linux/fs.md
This PR refines the language in the last third of the
fs.md file.
This section was more of a pleasure to refine than have
been the other two. I suspect this is due to greater
familiarity on my part now with the subject matter.
> doc: linux/fs.md third part (and last)

- docs/applications/zenfs.md
This PR refines the language in the "RocksDB with
ZenFS" page.
> doc: applications/zenfs.md

- docs/tools/util-linux.md
This PR refines the English language in
tools/util-linux.md. It also updates a link
to the GitHub repository that hosts the
util-linux project.
> doc: rewrite /docs/tools/util-linux.md

- docs/tools/zns.md
This PR improves the English in the /docs/tools/
zns.md file.
> doc/tools: refine zns.md

- docs/tools/sg3utils.md
This PR refines the English in the sg3utils.md
file.
> docs/tools/sg3utils: refine sg3utils.md

- docs/community/devices.md
- docs/community/support.md
- docusaurus.config.js
- package.json
Make the neccesary changes to move to the 2.0.0-beta15 release.
Signed-off-by: Matias Bjørling <matias.bjorling@wdc.com>
> doc: upgrade to docusaurus 2.0.0-beta15

- docs/tools/libzbc.md
This PR refines the English in the libzbc.md file.
It contains one TODO, which awaits Damien's judgment.
> doc/tools/libzbc.md - refine libzbc.md

- docs/tools/libzbd.md
This PR refines the English in the libzbd.md file.
> docs/tools/libzbd.md - refine libzbd.md

- docs/tools/libnvme.md
This PR refines the language in tools/libnvme.md.
> doc/tools: refine libnvme.md

- docs/tools/qemu.md
This PR refines the English in tools/qemu.md.
It also makes some structural changes, and includes
some new compositions of information. For this reason,
it should be carefully examined to make certain that I
have not introduced technical errors or misrepresentations
into the text.
This represents the first serious alteration to a section
of the Zoned Storage documentation that I have made. If it
is a success, future PRs will be more like this than like
the ones that preceded it.
> doc/tools: refine qemu.md

- docs/tools/tcmu-runner.md
This PR refines the English in tcmu-runner.md.
> doc/tools: refine tcmu-runner.md

- README.md
Signed-off-by: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>
> README: Add prerequisites instructions for macOS

- docs/getting-started/smr-disk.md
s/devide/divide
I also reworded a sentence so that it reads as though
it is written by a native English speaker. Which it is.
> doc/getting-started: fix para in smr-disk.md

- docs/getting-started/smr-disk.md
This PR makes minor but crucial syntactical changes to
the English in the front matter of the "Getting Started
with SMR Hard-Disks" chapter of the Getting Started Guide.
It might be that this little section means to say:
1. Drive Managed Interfaces are irrelevant to ZonedStorage.
2. Host Aware devices will work with ZonedStorage, but
ZonedStorage treats them the way that it treats Host
Managed devices (which is to say that it does not support
random write capabilities, but instead respects the strong
sequential write constraints imposed by the Zoned Block
Interface).
If this list of two things does indeed preserve the intent of
this section, then I might return in the future to recast
this information more pithily. I set this comment down in
print here as a note to a future version of me, …
> doc: improve getting-started/smr-disk.md 1st Sect

- CODE_OF_CONDUCT.md
- COPYING
- LICENSE
- README.md
Add missing license information
Went with GPL-3. 
Removed the WD copyright notice, as it will be superseeded by the license.
> Add License information
